name: Auto Merge pull requests

on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

jobs:
  automerge:
    if: ${{ github.event.pull_request.base.ref == 'master' || github.event.pull_request.base.ref == 'staging' }}
    runs-on: ubuntu-latest
    steps:
      # Check for all current approvals if they match with appropriate GH team
      - name: Checking for PR permissions
        env:
          GH_TEAM: ${{ github.event.pull_request.base.ref == 'master' && 'nexera_prod' || 'nexera_staging' }}
        shell: bash
        run: |
          function exists_in_list() {
              LIST=$1
              DELIMITER=$2
              VALUE=$3
              LIST_WHITESPACES=$(echo "$LIST" | tr "$DELIMITER" " ")
              for x in $LIST_WHITESPACES; do
                if [ "$x" = "$VALUE" ]; then
                  return 0
                fi
              done
              return 1
          }

          approvedUsers=($(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MERGE_BOT_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/UnbloktTechnology/ComPilot-Examples/pulls/${{ github.event.pull_request.number }}/reviews | jq -r '.[] | select(.state == "APPROVED") | .user.id'))

          teamUserIDs=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MERGE_BOT_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/UnbloktTechnology/teams/${{ env.GH_TEAM }}/members | jq  -r '.[].id')

          COUNTER=0
          for value in "${approvedUsers[@]}"
          do
            if exists_in_list "$teamUserIDs" " " $value; then
              echo "$value is a valid user from the users list which are allowed to merge"
              COUNTER=$((COUNTER+1))
            else
              echo "$value is NOT in the list of valid users to merge"
            fi
          done
          
          if [[ $COUNTER -gt 0 ]] ; then
            echo "Allowed to merge."
          else
            echo "Not merging."
            exit 1
          fi

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.MERGE_BOT_APP_ID }}
          private_key: ${{ secrets.MERGE_BOT_PRIVATE_KEY }}

      - name: Enable merge commits
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.MERGE_BOT_ACCESS_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/UnbloktTechnology/ComPilot-Examples \
            -d '{"allow_merge_commit":true}' \
            --output /dev/null

      - name: Automatic merge
        id: auto-merge
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          MERGE_METHOD: merge
          LOG: DEBUG
          MERGE_RETRIES: 60 # Attempts to merge 60 times every 20 seconds (so workflows can finish)
          MERGE_RETRY_SLEEP: 20000 # Milliseconds
          UPDATE_LABELS: none

      - name: Disable merge commits
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.MERGE_BOT_ACCESS_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/UnbloktTechnology/ComPilot-Examples \
            -d '{"allow_merge_commit":false}' \
            --output /dev/null
